databases:
  - name: todolist
    databaseName: todolist_mlik
    user: todolist_mlik_user

services:
  - type: web
    name: todolist-service
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: todolist
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false